apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: backend-sonarqube-
  namespace: smart-mobility-dev
spec:
  pipelineRef:
    name: backend-sonarqube-pipeline
  params:
    - name: GIT_URL
      value: https://github.com/kmotojim/smart-mobility-dashboard.git
    - name: GIT_REVISION
      value: main
    - name: SOURCE_PATH
      value: backend
    - name: SONAR_HOST_URL
      value: http://docker-sonarqube-git.sonarqube.svc.cluster.local:9000
    - name: SONAR_PROJECT_KEY
      value: smart-mobility-backend
    - name: SONAR_TOKEN
      value: "<YOUR_SONAR_TOKEN>"
    - name: DOCKERFILE_PATH
      value: ./backend/Dockerfile
    - name: INTERNAL_REGISTRY_URL
      value: image-registry.openshift-image-registry.svc:5000/smart-mobility-dev/smart-mobility-backend
    - name: EXTERNAL_REGISTRY_URL
      value: quay.io/rh_ee_kmotojim/smart-mobility-backend
    - name: IMAGE_TAG
      value: latest
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: pipeline-workspace-pvc
